import { Poppins } from "next/font/google";
import "./globals.css";
import FooterWrapper from "@/components/homepage/FooterWrapper";
import { ClerkProvider } from "@clerk/nextjs";

const poppins = Poppins({
  weight: ['400', '500', '700'],
  subsets: ['latin'],
  display: 'swap',
});

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <ClerkProvider>
      <html lang="en">
        <body
          className={` ${poppins.className} antialiased`}
        >
          <div className="min-h-screen pb-50">
            {children}
          </div>
          <FooterWrapper />
        </body>
      </html>
    </ClerkProvider>
  );
}
